[changelog]
header = "# Changelog"
body = """
## [{{ version }}] - {{ timestamp }}
{{ commits }}
"""

[git]
conventional_commits = true
split_commits_by_tag = true

[commit_parsers]
"feat" = "âœ¨ Features"
"fix" = "ğŸ› Bug Fixes"
"chore" = "ğŸ›  Maintenance"
"docs" = "ğŸ“– Documentation"
"refactor" = "â™»ï¸ Refactor"
"perf" = "ğŸš€ Performance"
"test" = "ğŸ§ª Testing"
"default" = "ğŸ“Œ Other Changes"

[filters]
exclude_merge_commits = true
